DROP DATABASE IF EXISTS lez06_oto_anagrafe;
CREATE DATABASE lez06_oto_anagrafe;
USE lez06_oto_anagrafe;

CREATE TABLE Persona(
	personaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(250) NOT NULL,
    cognome VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE CartaIdentita(
	cartaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    codice VARCHAR(10) NOT NULL UNIQUE,
    scadenza DATE NOT NULL,
    personaRIF INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (personaRIF) REFERENCES Persona(personaID) ON DELETE CASCADE
);